CREATE TABLE IF NOT EXISTS focal (
  user_id INT UNSIGNED NOT NULL,
  full_name VARCHAR(120) NULL,
  contact_no VARCHAR(40) NULL,
  address VARCHAR(180) NULL,
  date_of_birth DATE NULL,
  place_of_birth VARCHAR(120) NULL,
  age INT NULL,
  sex ENUM('Male','Female') NULL,
  bachelor_degree VARCHAR(120) NULL,
  religion VARCHAR(80) NULL,
  blood_type VARCHAR(10) NULL,
  nationality VARCHAR(60) NULL,
  civil_status VARCHAR(30) NULL,
  weight_kg DECIMAL(5,2) NULL,
  height_ft VARCHAR(5) NULL,
  emergency_contact_name VARCHAR(120) NULL,
  emergency_contact_no VARCHAR(40) NULL,
  emergency_contact_address VARCHAR(180) NULL,
  profile_photo_path VARCHAR(500) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_focal_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO focal (
  user_id,
  full_name,
  contact_no,
  address,
  date_of_birth,
  place_of_birth,
  age,
  sex,
  bachelor_degree,
  religion,
  blood_type,
  nationality,
  civil_status,
  weight_kg,
  height_ft,
  emergency_contact_name,
  emergency_contact_no,
  emergency_contact_address,
  profile_photo_path,
  created_at,
  updated_at
)
SELECT
  t.user_id,
  t.full_name,
  t.contact_no,
  t.address,
  t.date_of_birth,
  t.place_of_birth,
  t.age,
  t.sex,
  t.bachelor_degree,
  t.religion,
  t.blood_type,
  t.nationality,
  t.civil_status,
  t.weight_kg,
  t.height_ft,
  t.emergency_contact_name,
  t.emergency_contact_no,
  t.emergency_contact_address,
  t.profile_photo_path,
  COALESCE(t.created_at, NOW()),
  COALESCE(t.updated_at, NOW())
FROM teachers t
JOIN users u ON u.id = t.user_id
WHERE u.role = 'focal'
ON DUPLICATE KEY UPDATE
  full_name = VALUES(full_name),
  contact_no = VALUES(contact_no),
  address = VALUES(address),
  date_of_birth = VALUES(date_of_birth),
  place_of_birth = VALUES(place_of_birth),
  age = VALUES(age),
  sex = VALUES(sex),
  bachelor_degree = VALUES(bachelor_degree),
  religion = VALUES(religion),
  blood_type = VALUES(blood_type),
  nationality = VALUES(nationality),
  civil_status = VALUES(civil_status),
  weight_kg = VALUES(weight_kg),
  height_ft = VALUES(height_ft),
  emergency_contact_name = VALUES(emergency_contact_name),
  emergency_contact_no = VALUES(emergency_contact_no),
  emergency_contact_address = VALUES(emergency_contact_address),
  profile_photo_path = VALUES(profile_photo_path),
  updated_at = VALUES(updated_at);
